alecthomas/entityx

entityx/Entity.h
Using `replace` avoids the client-side song and dance around assignment in cases where a component of the same type may already be assigned to the entity. This is a suggestion related to my mailing list question.
=> Entity::replace<Component> method.

entityx/Entity.h
Remove the user defined constructors for Entity that are equivalent to the compiler generated ones.
Allows Entity to be trivially copyable.
=> Remove user defined constructors for Entity 

README.md
Otherwise you get an error when trying to run the example.
/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/entityx/entityx/Event.h: In instantiation of ‘void entityx::EventManager::subscribe(Receiver&) [with E = PlayerInstrucionEvent; Receiver = MovementSystem]’:
/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/src/system_movement.hpp:17:58:   required from here
/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/entityx/entityx/Event.h:130:26: error: ‘entityx::BaseReceiver’ is an inaccessible base of ‘MovementSystem’
BaseReceiver &base = receiver;
=> Make Receiver inheritance public instead of implicitly private

entityx/Entity.h
The number of entities is limited to 2^32 so capacity will never exceed that number, so this code is safe.
=> Fix size downcast warning on 64 bit builds.

CMakeLists.txt
Fixes issue with project linking with a release entityx.dll when building in debug mode.
=> Generate seperate debug postfix dll for building in debug.

CMakeLists.txt
Fixes issue #113.
Single quote use of literal 'MSVC'.
Remove use of quoted variables inside if and elseif blocks.
=> Fix CMP0054 warnings in CMake >= 3.1

CMakeLists.txt, entityx/Benchmarks_test.cc
Fixes #122 
- Enables building, but not running benchmark tests when BUILD_TESTING is enabled. 
- Fixes uint64_t ambigutity issue on compiling Benchmark_tests.cc on MSVC
=> Pr uint64fix

README.md, entityx/ComponentHandle.h, entityx/Entity.h, entityx/EntityClass.h, entityx/Entity_test.cc, entityx/help/Pool.h, entityx/help/Pool_test.cc
This PR introduces the behavior of emitting a `ComponentRemovedEvent` for each of an `Entity`'s components when it is destroyed. This was discussed in #107.
This alters the behavior of the `EntityDestroyedEvent` since it made more sense to me to emit the  `ComponentRemovedEvent`s before the `EntityDestroyedEvent`, since that is similar to how a destructor would work. This change, of course, can be reverted.
=> Emit ComponentRemovedEvent<T> on Entity::destroy()

entityx/Entity.h, entityx/Entity_test.cc
This PR enables the ability to create a component-wise clone of an entity. Each component is copy-constructed by using the existing `assign_from_copy` method.
A test has been added which shows that the component is copied but is unique.
This implements the feature requested in #126.
=> Enable Entity cloning via EntityManager::create_from_copy

CMakeLists.txt, entityx/Entity.h
- Added a function to retrieve the Entity associated with a component in ComponentHandle.
- Fixed that when ENTITYX_BUILD_SHARED=1 was compiling the static library and the shared_library. Now it only compiles one of them, shared or static, but not both. Using visual studio compiler, now, the shared library doesn't create a .lib file (because it doesn't export anything which is OK).
=> Fixed shared library compilation and Function to retrieve the entity from ComponentHandle

CMakeLists.txt
This makes it very easy to integrate entityx into a build.
I.e:
add_subdirectories(3rdparty/entityx)
target_link_libraries(my_target entityx[_shared])
This makes #include "entityx/entityx.h" just work.
=> Set build_interface directories for integrated builds

entityx/entityx.hh
This allows `EntityX::valid` to be used in situations where we have (e.g.) a const reference to an entity manager.
I've verified that the example SFML 2 application and `entity_test` both compile and run/pass with this change.
=> Mark EntityX::valid as const

CMakeLists.txt
First, thank you for making entityx! I think it's a great library, easy to use and works very well. A few months ago, I started looking into the ECS approach for a new project, and was almost at the point where I considered creating my own implementation, but then I found entityx and it did everything I needed, so I went with it :)
This is a fairly minor cosmetic improvement, but I still find it useful, since I'm using cmake-gui a lot when developing on Windows. Prior to the changes in this branch, the output from cmake-gui would look like this:
When setting the `mode` to `STATUS` for the `message()` command, it instead looks like the following, which I believe is closer to how it's intended?
Note: I'm bundling entityx into my project using a submodule, instead of using it as an external …
=> CMake: Use 'STATUS' message type for non-error messages

CMakeLists.txt
A one-word fix in copy&paste mistake in the section for checking C++11 features.
=> Fix copy&paste mistake in CMakeLists.txt

entityx/Entity.h, entityx/Entity_test.cc
This makes it possible to write code like this:
```cpp
auto& componentRef = *someEntity.component<Position>();
componentRef.x += 2;
```
This was already possible previously, but required calling `.get()` on the component handle in addition to dereferencing. Having this operator also makes the component handle more consistent with common smart pointer types, since it already has the `->` operator.
I wasn't sure whether it makes sense to add a test for something so trivial, but I did for now.
=> Add dereference operator to ComponentHandle

entityx/entityx.hh
You were right.. it's useless to receive an entity destruction after the destruction of the components.
And There are situations where you want ordered destruction of components, so this change is needed to remove the components in order when a on_destroy_entity is emitted.
=> First emit entity destruction then emit each remaining component destruction

entityx/entityx.hh
Previously, ContiguousStorage did not deallocate on destruction and
would leak memory when an EntityManager was destructed.  An example
valgrind transcript on entity_test demonstrates this:
$ valgrind --leak-check=full ./entity_test
[...output elided...]
===============================================================================
All tests passed (538 assertions in 28 test cases)
==21061==
==21061== HEAP SUMMARY:
==21061==     in use at exit: 1,600 bytes in 20 blocks
==21061==   total heap usage: 9,001 allocs, 8,981 frees, 54,582,761 bytes allocated
==21061==
==21061== 800 bytes in 10 blocks are definitely lost in loss record 1 of 2
==21061==    at 0x4C2D8CF: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21061==    by 0x1332D9: resize …
=> Make ContiguousStorage deallocate on destruction

entityx/entityx.hh, tests/entity_test.cc
`EntityX::components()` requires the entity ID in both its non-const and
const variants, but` Entity::components()` passed said ID in only one such
variant.
This commit also includes a test (almost identical to the existing
`Entity::components()` test) to exercise the compiler on this code path.
=> Add missing argument in Entity::components() const

entityx/3rdparty/simplesignal.h, entityx/help/Pool_test.cc
The test leak doesn't particularly matter, but simplesignal.h has a minor direct leak when using the size() function for receivers. I recently submitted the fix to that repository as well, it was a quick one-liner but it seems the entityx/simplesignal.h is a couple commits behind.
Should be able to see the leaks when you add -fsanitize=address to the debug flags and run event_test and pool_test.
=> Fix minor memory leak from simplesignal.h and inside pool_test.cc

entityx/Entity.h, entityx/Entity_test.cc, entityx/Event.h, entityx/System.h, entityx/System_test.cc
As discussed in #212, update relevant initialisation locations to use `{}` instead of `()`. Also updated tests to pass the right types to avoid narrowing conversion errors.
=> Update to brace initialisation to allow for easy aggregate use

README.md
EntityX is now an official Arch Linux package and this is all that is required for installing [entityx](https://www.archlinux.org/packages/community/x86_64/entityx/) (including libraries, headers, pkg-config files and everything) on Arch Linux:
pacman -S entityx
=> Add note about Arch Linux

README.md
`entityx` is now available as a formula in Homebrew. Updated the README to reflect this.
=> Installation using Homebrew

CMakeLists.txt
Library debug postfix might not be suitable for cross platform project, and usually require extra work of link against prebuilt entityx.
Generally, Xcode project output library to these directories:
```
Debug
Release
Debug-iphoneos
Release-iphoneos
Debug-iphonesimulator
Release-iphonesimulator
```
Another Xcode project usually configured its build setting as follow, and expects library name to be same between Release and Debug
```
LIBRARY_SEARCH_PATHS=$(CONFIGURATION)$(EFFECT_PLATFORM_NAME)
OTHER_LDFLAGS= $(inherited) -lentityx
```
=> Make debug postfix optional

entityx/3rdparty/catch.hpp
Hello,
I was having  issues compiling on Ubuntu 20.04 64 bit with gcc 9.3.0. The issue seemed to be related to the Catch library.
The errors look like:
> In file included from /home/jarrett/projects/entityx/entityx/help/Pool_test.cc:14:
> /home/jarrett/projects/entityx/entityx/3rdparty/catch.hpp: In member function ‘Catch::AssertionInfo& Catch::AssertionInfo::operator=(const Catch::AssertionInfo&)’:
> /home/jarrett/projects/entityx/entityx/3rdparty/catch.hpp:943:12: error: implicitly-declared ‘Catch::SourceLineInfo& Catch::SourceLineInfo::operator=(const Catch::SourceLineInfo&)’ is deprecated [-Werror=deprecated-copy]
>   943 |     struct AssertionInfo
>       |            ^~~~~~~~~~~~~
> In file included from /home/jarrett/projects/entityx/entityx/help/Pool_test.cc:14:
> …
=> Updated Catch library to v1.12.2

CMakeLists.txt
This addresses the potential silent failure of attempting to build EntityX as a shared library with MSVC, seen in #160, #186, #206, #246, and others.  It is expressed as a warning instead of a fatal error to permit the "workaround" found in multiple comments on those issues.  
With this warning emitted at configuration-time, it is made clear to the end-user that this is an unsupported option on their platform, saving potential time and effort diagnosing the issue or reporting it as a bug.
=> Add warning for unsupported configuration in MSVC.
